### ISSUE TITLE
Migrations SQL script (npgsql) truncates some identifiers to 64 not 63 characters

### ISSUE THREAD

**Issue by markm77** [efcore/EFCore.NamingConventions#141]
I raised an issue in the main EF Core repo but seems the root cause is with EFCore.NamingConventions.

See issue details here:
https://github.com/dotnet/efcore/issues/27862

**Comment by roji** [comment]
@markm77 apologies for not getting around to looking at this.

It's quite a bit later, and I'm trying to take a look at this again, but am not able to repro the problem. Running the repro in https://github.com/dotnet/efcore/issues/27862#issuecomment-1118911340 produces the following SQL (am using the latest main, which will be published as 8.0.0 very soon):

```sql
CREATE TABLE account_access_consent (
  id uuid NOT NULL,
  bank_registration_id uuid NOT NULL,
  CONSTRAINT pk_account_access_consent PRIMARY KEY (id),
  CONSTRAINT fk_account_access_consent_bank_registration_bank_registration_ FOREIGN KEY (bank_registration_id) REFERENCES bank_registration (id) ON DELETE CASCADE
);
```

The long constraint name here is `fk_account_access_consent_bank_registration_bank_registration_`, which is 62 characters long (why it isn't 63 is another question...).

As this has been open for a while, it's possible that this was simply fixed in the meantime; I'll go ahead and close this. However, if you'd like to test with and report back, I'd be happy to reopen this and investigate as needed.

**Comment by markm77** [comment]
Hi @roji ,

Thanks for the response and test. Sure I can test this again after the next round of .NET 8 updates come along. I want to check out .NET 8 anyway to try the new PostgreSQL JSON stuff. 🙂

Note: this issue has caused no problem in practice and I've done many migrations since I hit this.

BR,
Mark

**Comment by roji** [comment]
@markm77 thank you! Yeah, it would be great to get confirmation when you get some spare time.
