### ISSUE TITLE
naming conventions on views name and columns

### ISSUE THREAD

**Issue by sara82v** [efcore/EFCore.NamingConventions#193]
Is it possible to extend the naming convention also in views?
Thanks

**Comment by roji** [comment]
@sara82v sorry for not answering earlier.

The plugin does support views, although that's less well-tested than other usage scenarios. Since this issue is quite old, I'll go ahead and close it - but if you're hitting a problem using views, please post back with a minimal, runnable code sample and I'll do my best to investigate.
