### ISSUE TITLE
Question - Are there a similar project for datatypes

### ISSUE THREAD

**Issue by Martin-Andersen** [efcore/EFCore.NamingConventions#37]
Hi I am using your project for following Oracle naming conventions. Do you know of a similar project for setting datatypes?

string should default to varchar2 and the list goes on (:

**Comment by roji** [comment]
@Martin-Andersen are you asking how to determine what .NET string properties should be mapped to in the database? If so, that's not really related to naming conventions, which manage the names of tables, columns and the like. You may be looking for [these docs](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-data-types).

Otherwise, post back here with more details and I'll try to help.
